In [2]:
import pandas as pd

In [32]:
data = pd.read_csv('Energy_and_Water_Use_-_Municipal_Buildings.csv')

In [129]:
data.iloc[:,[0,8,7,13]][(data['water_use_all_water_sources_kgal']==data.water_use_all_water_sources_kgal.idxmax()) |
                       (data['water_use_all_water_sources_kgal'] ==data.water_use_all_water_sources_kgal.max()) ]

,cartodb_id,property_name,department,water_use_all_water_sources_kgal
199,200,Sanitation: 21/32 Gaffey St Yard,Sanitation:,20040.1

In [72]:
data['department'].groupby(data['department']).describe()

            count unique          top freq
department
Animal         14      1       Animal   14
CDD:            2      1         CDD:    2
Cultural        6      1     Cultural    6
DOT:           13      1         DOT:   13
Fire          135      1         Fire  135
GSD            14      1          GSD   14
ITA:            2      1         ITA:    2
Libraries:    143      1   Libraries:  143
Municipal      45      1    Municipal   45
Municipal:      2      1   Municipal:    2
Personnel       4      1    Personnel    4
Police         60      1       Police   60
Public          2      1       Public    2
Residence:      2      1   Residence:    2
Sanitation:    13      1  Sanitation:   13
Street         11      1       Street   11

In [80]:
data.iloc[:,[1,8,7,12]].sort_values('total_ghg_emissions_metric_tons_co2e',ascending=0)[(data['total_ghg_emissions_metric_tons_co2e'] ==  data['total_ghg_emissions_metric_tons_co2e'])].head()

C:\Users\Sui\AppData\Local\conda\conda\envs\rstudio\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,the_geom,property_name,department,total_ghg_emissions_metric_tons_co2e
4,0101000020E610000063416150A68F5DC01903EB387E06...,Municipal: 1/14 City Hall East,Municipal,6656.9
5,0101000020E61000002A8E03AF968F5DC079AC1919E406...,Municipal: 1/2 Los Angeles City Hall,Municipal,4414.9
244,0101000020E61000008B4F01309E8F5DC0B69E211CB306...,Police Department: 9/63 Police Administratio...,Police,3338.3
0,0101000020E61000008B4F01309E8F5DC0B69E211CB306...,Police Department: 9/63 Police Administratio...,Police,3287.3
14,0101000020E6100000A6EF3504C78E5DC0DE5A26C3F106...,Municipal: 1/18 Piper Tech,Municipal,3101.8

In [95]:
data.iloc[:,[0,7,8,3]][(data['energy_star_score '] >=75)].sort_values(by='energy_star_score ',ascending=0)

,cartodb_id,department,property_name,energy_star_score
238,239,Personnel,Personnel Department: Personnel Medical Svc D...,100
241,242,GSD,"GSD Facilities: 7th street shops, yards, offic...",100
464,465,Personnel,Personnel Department: Personnel Medical Svc D...,100
248,249,Municipal,Municipal: 1/44 Fig Plaza II,96
217,218,Municipal,Municipal: 1/4 Sunland Tujnga Municipal,91
440,441,Municipal,Municipal: 1/99 Wilmington Municipal,91
436,437,Municipal,Municipal: 1/7 Watts Municipal,90
445,446,Municipal,Municipal: 1/4 Sunland Tujnga Municipal,90
247,248,Public,Public Works: Transamerica Public works 1/88,87
3,4,Public,Public Works: Transamerica Public works 1/88,85
212,213,Municipal,Municipal: 1/99 Wilmington Municipal,85
207,208,Municipal,Municipal: 1/7 Watts Municipal,84
442,443,Municipal,Municipal: 1/3 San Pedro Municipal,76
214,215,Municipal:,Municipal: 1/3 San Pedro Municipal,75

In [130]:
data.groupby(['year_ending'])['water_use_all_water_sources_kgal'].max()

year_ending
31-Dec-14    20040.1
31-Dec-15    12601.7
Name: water_use_all_water_sources_kgal, dtype: float64

In [133]:
df1 = pd.DataFrame(data, columns = ['weather_normalized_site_eui_kbtu_ft','weather_normalized_source_eui_kbtu_ft'])
df2 = pd.DataFrame(data, columns = ['weather_normalized_site_eui_kbtu_ft','weather_normalized_source_eui_kbtu_ft'])

EffTrans = data.concat([df1, df2])

AttributeError: 'DataFrame' object has no attribute 'concat'

In [144]:
data['EffTrans'] = data['weather_normalized_site_eui_kbtu_ft']/data['weather_normalized_source_eui_kbtu_ft']
data.iloc[:,[0,7,8,15,14,19]][(data['weather_normalized_site_eui_kbtu_ft'] >0)]

,cartodb_id,department,property_name,weather_normalized_site_eui_kbtu_ft,weather_normalized_source_eui_kbtu_ft,Result
0,1,Police,Police Department: 9/63 Police Administratio...,89.7,211.6,0.423913
1,2,Municipal,LA Buildings - not tracked: 12/3 Street Light...,2821.7,8860.1,0.318473
2,3,Municipal,LA Buildings - not tracked: 12/4 Street Light...,695.3,2183.4,0.318448
4,5,Municipal,Municipal: 1/14 City Hall East,163.4,426.6,0.383029
5,6,Municipal,Municipal: 1/2 Los Angeles City Hall,148.7,303.7,0.489628
7,8,Police,Police Department: 9/83 911 Valley Communi...,165.3,514.3,0.321408
9,10,Police,Police Department: 9/20 Central Facilities Bu...,281.5,770.0,0.365584
10,11,ITA:,ITA: 1/9 Mount Lee,711.7,2234.9,0.318448
11,12,Police,Police Department: 9/5 EOC Emergency Operatio...,129.0,384.7,0.335326
12,13,Libraries:,Libraries: 51/100 Central Library,58.6,149.2,0.392761
15,16,Police,Police Department: 9/7 77th Street Police,96.3,233.2,0.412950
17,18,Fire,Fire Department: 5/36 Fire Station #36,60.5,154.4,0.391839
18,19,Fire,Fire Department: 5/87 Fire Station #87,94.6,246.4,0.383929
20,21,Fire,Fire Department: 5/92 Fire Station #92,42.1,132.1,0.318698
21,22,Fire,Fire Department: 5/3 Fire Station #3,80.7,188.2,0.428799
22,23,Fire,Fire Department: 5/64 Fire Station #64,174.3,440.5,0.395687
23,24,Fire,Fire Department: 5/28 Fire Station #28,70.9,155.4,0.456242
24,25,Fire,Fire Department: 5/37 Fire Station #37,86.0,153.8,0.559168
25,26,Fire,Fire Department: 5/62 Fire Station #62,55.7,147.6,0.377371
26,27,Fire,Fire Department: 5/108 Fire Station #108,72.3,163.8,0.441392
27,28,Fire,Fire Department: 5/98 Fire Station #98,66.0,145.1,0.454859
28,29,Fire,Fire Department: Fire Station #85,61.1,147.0,0.415646
29,30,Fire,Fire Department: 5/27 Fire Station #27,26.8,84.2,0.318290
30,31,Fire,Fire Department: 5/10 Fire Station #10,51.2,119.4,0.428811
31,32,Fire,Fire Department: 5/401 Fire Station #401 Shop...,83.9,221.5,0.378781
33,34,Fire,Fire Department: 5/39 Fire Station #39,69.6,160.7,0.433105
34,35,Fire,Fire Department: 5/111 Fire Station #111,51.4,161.3,0.318661
35,36,Fire,Fire Department: 5/75 Fire Station #75,84.4,188.9,0.446797
36,37,Fire,Fire Department: 5/58 Fire Station #58,75.4,132.0,0.571212
38,39,Fire,Fire Department: 5/17 Fire Station #17,45.9,106.8,0.429775
...,...,...,...,...,...,...
432,433,Sanitation:,Sanitation: 21/1 North District Sewer Mainten...,107.9,262.0,0.411832
433,434,Sanitation:,Sanitation: 21/36 San Fernando Rd. Consolidate...,272.6,564.5,0.482905
434,435,Sanitation:,Sanitation: 20/4 West Valley Solid Waste recy...,871.4,1564.3,0.557054
435,436,Municipal,Municipal: 1/5 Van Nuys Municipal,119.3,300.3,0.397269
436,437,Municipal,Municipal: 1/7 Watts Municipal,30.6,82.8,0.369565
437,438,Municipal,Municipal: 1/8 West L.A. Municipal,63.8,177.5,0.359437
438,439,Municipal,Municipal: 1/46 Sawtelle Various City,52.4,164.6,0.318348
440,441,Municipal,Municipal: 1/99 Wilmington Municipal,25.0,71.0,0.352113
441,442,Municipal,Municipal: 1/96 Braude Building,94.8,237.9,0.398487
442,443,Municipal,Municipal: 1/3 San Pedro Municipal,45.6,122.8,0.371336
443,444,Municipal,Municipal: 1/13 Hollywood Municipal,199.2,415.4,0.479538
445,446,Municipal,Municipal: 1/4 Sunland Tujnga Municipal,38.6,82.0,0.470732
446,447,Municipal,Municipal: 1/19 Constituent Service Ctr So Ce...,157.3,323.2,0.486696
447,448,DOT:,DOT: 63/41 Western Parking Enforcement office,56.3,131.4,0.428463
449,450,DOT:,DOT: 63/15 Hollywood Area DOT,41.6,101.3,0.410661
451,452,Municipal,City of LA - removed properties: 63/26 Parkin...,8.4,26.3,0.319392
452,453,DOT:,DOT: 63/23 South Area Parking Management,59.5,171.2,0.347547
453,454,GSD,GSD Facilities: 1/72 North Hollywood Repair fa...,284.4,630.8,0.450856
454,455,GSD,GSD Facilities: 1/17 GSD North District Mainte...,146.3,347.4,0.421128
455,456,GSD,GSD Facilities: 1/111 Standards Test Labs,155.7,420.2,0.370538
456,457,GSD,GSD Facilities: 01/037 7th Street Complex (GSD),312.8,580.8,0.538567
457,458,GSD,GSD Facilities: 1/76 Central refuse equipment ...,112.2,229.6,0.488676
459,460,GSD,GSD Facilities: 1/47 36th St Building Maintena...,95.6,276.2,0.346126
461,462,Residence:,Residence: Getty House (30/3),57.4,126.3,0.454473
462,463,Police,Police Department: 9/41 North Valley Police,147.6,358.7,0.411486
463,464,Personnel,Personnel Department: Personnel building #27/8...,72.7,201.2,0.361332
464,465,Personnel,Personnel Department: Personnel Medical Svc D...,99.1,233.7,0.424048
465,466,Street,Street Lighting (BSL): 12/1 Street Lighting F...,28.1,81.6,0.344363
466,467,CDD:,CDD: CDD 47/88,46.6,137.8,0.338171
467,468,Animal,Animal Services: 7/9 South LA Animal Shelter ...,174.9,390.8,0.447544